name: Build Containers
on:
  release:
    types: [ created, edited ]
  workflow_dispatch:
    inputs:
      tag:
        description: 'tag'
        required: true
        default: 'latest'
        type: string
jobs:
  build:
    name: Build
    strategy:
      matrix:
        arch: [ amd64 ]
        version: [ 17-bookworm ]
    runs-on: ${{ matrix.arch == 'amd64' && 'ubuntu-latest' || matrix.arch == 'arm64' && 'nx1' }} # Builds on NX1 self-hosted
    env:
      ARCH: ${{ matrix.arch }}
      OS: linux
      VERSION: ${{ matrix.version }}
      DOCKER_REPO: ghcr.io/${{ github.repository }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push
        id: build      
        run: |
          make docker && make docker-push
  manifest:
    name: Manifest
    needs: build
    strategy:
      matrix:
        version: [ 17-bookworm ]
    runs-on: ubuntu-latest
    steps:
      - name: Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v5
        id: metadata
        with:
          images: ghcr.io/${{ github.repository }}
      - uses: int128/docker-manifest-create-action@v2
        id: manifest
        with:
          index-annotations: ${{ steps.metadata.outputs.labels }}
          tags: ${{ steps.metadata.outputs.tags }}
          sources: |
            ghcr.io/${{ github.repository }}@${{ matrix.version }}
            ghcr.io/${{ github.repository }}@${{ matrix.version }}
  
